[env]
DAVE_IO_MISE_ACTIVE = 'true'

[settings]
env_file = '.env'
idiomatic_version_file = false
idiomatic_version_file_enable_tools = []

[tools]
bun = { version = '1.3.4' }
node = { version = '25.2.1' }
rust = { version = '1.92.0' }

[tasks]
'cc' = { run = "claude", description = "Invoke Claude Code" }
