[env]
DAVE_IO_MISE_ACTIVE = 'true'

[settings]
env_file = '.env'

[tools]
bun = { version = '1.3.5' }
node = { version = '25.2.1' }
rust = { version = '1.92.0' }

[tasks]
'cc' = { run = "claude", description = "Invoke Claude Code" }
