name: ci
permissions: read-all
on:
  push: null
  pull_request: null
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
      - name: bun
        uses: oven-sh/setup-bun@b02f8a8a6ed27f2a73a9c46e4e01fb2ac0d22882
        with:
          bun-version: 1.2.20
      - name: install
        run: bun install
      - name: trunk
        uses: trunk-io/trunk-action@bf81325059d2534b31df5365182237788c5e0338
      - name: typecheck
        run: bun run lint:types
      - name: build
        run: bun run build
